"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.dict = exports.commonData = void 0;
var Dashboard_Owner_jpg_1 = require("../assets/project/Dashboard Owner.jpg");
var file_2024_06_01_04_49_33_png_1 = require("../assets/project/file_2024-06-01_04.49.33.png");
var file_2024_06_01_04_50_40_png_1 = require("../assets/project/file_2024-06-01_04.50.40.png");
var Coursera_SIIEEXK95VJ1_page_0001_jpg_1 = require("../assets/sertifikat/Coursera SIIEEXK95VJ1_page-0001.jpg");
var Coursera_UZJXQ81I09FB_page_0001_jpg_1 = require("../assets/sertifikat/Coursera UZJXQ81I09FB_page-0001.jpg");
var Coursera_V8PPR7G6J6L7_page_0001_jpg_1 = require("../assets/sertifikat/Coursera V8PPR7G6J6L7_page-0001.jpg");
var Coursera_L5GWHY2S65F3_page_0001_jpg_1 = require("../assets/sertifikat/Coursera L5GWHY2S65F3_page-0001.jpg");
var Coursera_NIBUU6LLFMPP_page_0001_jpg_1 = require("../assets/sertifikat/Coursera NIBUU6LLFMPP_page-0001.jpg");
var Coursera_Y5GPPKOQ0Z1V_page_0001_jpg_1 = require("../assets/sertifikat/Coursera Y5GPPKOQ0Z1V_page-0001.jpg");
var sertifikat_course_184_2958460_250624122158_page_0001_jpg_1 = require("../assets/sertifikat/sertifikat_course_184_2958460_250624122158_page-0001.jpg");
var sertifikat_course_555_2958460_051024142545_page_0001_jpg_1 = require("../assets/sertifikat/sertifikat_course_555_2958460_051024142545_page-0001.jpg");
exports.commonData = {
    socialLinks: [
        { label: 'Instagram', href: 'https://www.instagram.com/z1ee.e/' },
        { label: 'WhatsApp', href: 'https://wa.me/+6285236487807' },
        { label: 'LinkedIn', href: 'https://www.linkedin.com/in/moh-faried-al-farizi-0237b128b/' },
        { label: 'GitHub', href: 'https://github.com/ziee2' },
    ],
    stats: [
        { value: '3.90', labelId: 'IPK', labelEn: 'GPA' },
        { value: '3k+', labelId: 'Dataset dibersihkan', labelEn: 'Datasets cleaned' },
        { value: '98%', labelId: 'Akurasi terbaik', labelEn: 'Best accuracy' },
        { value: '400+', labelId: 'Jam pembelajaran', labelEn: 'Learning hours' },
    ],
    certificates: [
        { title: 'TensorFlow: Data and Deployment', issuer: 'Coursera', date: '2024', url: '#', image: Coursera_SIIEEXK95VJ1_page_0001_jpg_1.default },
        { title: 'DeepLearning.AI TensorFlow Developer', issuer: 'Coursera', date: '2024', url: '#', image: Coursera_UZJXQ81I09FB_page_0001_jpg_1.default },
        { title: 'Machine Learning', issuer: 'Coursera', date: '2024', url: '#', image: Coursera_V8PPR7G6J6L7_page_0001_jpg_1.default },
        { title: 'TensorFlow: Advanced Techniques', issuer: 'Coursera', date: '2024', url: '#', image: Coursera_L5GWHY2S65F3_page_0001_jpg_1.default },
        { title: 'Machine Learning Terapan', issuer: 'Dicoding', date: '2024', url: '#', image: Coursera_NIBUU6LLFMPP_page_0001_jpg_1.default },
        { title: 'Belajar Fundamental Deep Learning', issuer: 'Dicoding', date: '2024', url: '#', image: Coursera_Y5GPPKOQ0Z1V_page_0001_jpg_1.default },
        { title: 'Build Better GANs', issuer: 'Coursera', date: '2024', url: '#', image: sertifikat_course_184_2958460_250624122158_page_0001_jpg_1.default },
        { title: 'NLP with Classification and Vector Spaces', issuer: 'Coursera', date: '2024', url: '#', image: sertifikat_course_555_2958460_051024142545_page_0001_jpg_1.default },
    ]
};
exports.dict = {
    id: {
        nav: [
            { id: 'about', label: 'Tentang' },
            { id: 'experience', label: 'Pengalaman' },
            { id: 'projects', label: 'Proyek' },
            { id: 'skills', label: 'Keahlian' },
            { id: 'certificates', label: 'Sertifikat' },
        ],
        hero: {
            badge: 'Portofolio AI Premium',
            title: 'Membangun sistem AI praktis untuk masalah dunia nyata.',
            desc: 'Lulusan Ilmu Komputer dari Universitas Jember dengan fokus pada Computer Vision, NLP, data cleansing, dan deployment model. Desain ini disusun agar profilmu terbaca lebih premium, tenang, dan kuat untuk kebutuhan rekrutmen.',
            exploreBtn: 'Jelajahi Proyek',
            proofBtn: 'Lihat Bukti',
            profileSnapshot: 'Cuplikan profil',
            profileSubtitle: 'Fokus AI dengan pengalaman proyek mendalam',
            currentDirection: 'Arah saat ini',
            currentDirectionDesc: 'dengan fokus pada computer vision, NLP, pipeline data, dan deployment siap produksi.',
        },
        valueProps: [
            'Saya membangun produk AI, bukan hanya melatih model.',
            'Pendekatan saya menggabungkan riset dan implementasi langsung.',
            'Struktur portofolio dibuat editorial agar cepat dipahami HR.',
            'Bukti kerja ditampilkan lewat visual proyek, dashboard, dan sertifikat.',
        ],
        sections: {
            about: {
                title: 'Tentang Saya',
                copy: 'Fresh graduate dengan spesialisasi di bidang Kecerdasan Buatan (AI), khususnya Computer Vision dan Natural Language Processing (NLP). Berpengalaman dalam membangun solusi inovatif secara end-to-end, mulai dari pengembangan model machine learning (TensorFlow, PyTorch), analisis data dengan Python, hingga deployment model sebagai REST API menggunakan Flask, FastAPI, dan Docker. Terbiasa bekerja secara sistematis dan terorganisir, siap berkontribusi dalam tim yang dinamis untuk mengembangkan produk AI dan memecahkan tantangan nyata di industri.',
                bgTitle: 'Edukasi & Pencapaian',
                bgSchool: 'Universitas Jember',
                bgLogo: 'https://upload.wikimedia.org/wikipedia/id/3/3a/Logo_Universitas_Jember.png',
                bgPeriod: '2021 - Sekarang',
                bgGpa: '3.90 / 4.00',
                bgDegree: 'S1 Informatika, Fakultas Ilmu Komputer',
                bgThesis: 'Skripsi: Perbandingan performa ResNet50V2, EfficientNetB4, dan DenseNet201 pada Mask R-CNN untuk segmentasi penyakit karat daun apel.',
                achTitle: 'Pencapaian',
                achSubtitle: 'Kompetitif, praktis, dan berbasis proyek',
                achDesc: 'Finalis Lomba Inovasi Digital Mahasiswa, Juara 3 Pengembangan Laos oleh UKM Linux & Open Source, dan Graduate Distinction dari Bangkit Academy.'
            },
            experience: {
                title: 'Pengalaman',
                copy: 'Saya terapkan format timeline profesional: setiap fase kerja punya visual, konteks, tools, dan impact yang jelas sehingga progression kamu lebih kuat di mata HR.',
                items: [
                    {
                        period: 'Februari - April 2026',
                        title: 'Software Development',
                        org: 'Freelance',
                        image: [Dashboard_Owner_jpg_1.default, file_2024_06_01_04_50_40_png_1.default, file_2024_06_01_04_49_33_png_1.default],
                        focus: 'Full-Stack Web Development & AI Integration',
                        impact: 'Meningkatkan otomatisasi operasional apotek melalui sistem POS berbasis web yang terintegrasi dengan AI.',
                        summary: 'Merancang dan membangun aplikasi web secara mandiri dari nol (Full-Stack), mengelola seluruh siklus pengembangan mulai dari antarmuka pengguna (Front-End) hingga sistem server dan basis data (Back-End). Membangun sistem kasir (POS) dan manajemen inventaris apotek berbasis web, mengintegrasikan fitur Artificial Intelligence (AI) khusus untuk meningkatkan otomatisasi operasional, serta dilengkapi sistem hak akses dan manajemen shift karyawan.',
                        tools: ['Full-Stack', 'Web App', 'AI Integration', 'POS'],
                        highlights: [
                            'Merancang dan membangun aplikasi web secara mandiri dari nol (Full-Stack).',
                            'Mengelola seluruh siklus pengembangan (Front-End hingga Back-End).',
                            'Membangun sistem kasir (POS) dan manajemen inventaris apotek.',
                            'Mengintegrasikan fitur Artificial Intelligence (AI) untuk otomatisasi operasional.',
                            'Mengimplementasikan sistem hak akses dan manajemen shift karyawan.'
                        ]
                    },
                    {
                        period: 'Sep - Des 2025',
                        title: 'Asisten Praktikum',
                        org: 'Lab. AI Universitas Jember',
                        image: [file_2024_06_01_04_49_33_png_1.default, file_2024_06_01_04_50_40_png_1.default, Dashboard_Owner_jpg_1.default],
                        focus: 'Edukasi AI dan dukungan laboratorium',
                        impact: 'Membantu mahasiswa memahami computer vision, visualisasi, dan implementasi deep learning melalui sesi panduan dan umpan balik tugas.',
                        summary: 'Memandu sesi lab untuk Computer Vision dan Visualisasi Data menggunakan Python, OpenCV, TensorFlow, dan library visualisasi. Menyiapkan materi, mendemonstrasikan teknik, dan mengevaluasi tugas terkait pemrosesan gambar dan deep learning.',
                        tools: ['Python', 'OpenCV', 'TensorFlow'],
                        highlights: [
                            'Memandu sesi praktikum untuk 50+ mahasiswa mengenai Computer Vision dan Visualisasi Data.',
                            'Menyusun materi praktikum berbasis Python, OpenCV, dan library visualisasi terkini.',
                            'Mendemonstrasikan teknik deep learning dan mengevaluasi implementasi mahasiswa.',
                            'Membantu penyelesaian error pada model TensorFlow yang dibangun oleh mahasiswa.'
                        ],
                        demoUrl: 'https://unej.ac.id'
                    },
                    {
                        period: 'Feb - Jun 2025',
                        title: 'Data Scientist Intern',
                        org: 'Social Economic Accelerator Lab (SEAL)',
                        image: [file_2024_06_01_04_50_40_png_1.default, file_2024_06_01_04_49_33_png_1.default, Dashboard_Owner_jpg_1.default],
                        focus: 'Data engineering dan cleansing',
                        impact: 'Meningkatkan konsistensi dataset di 3.000+ data pemerintah dan mengurangi masalah penggabungan melalui alur pencocokan semantik.',
                        summary: 'Membangun modul pembersihan otomatis untuk 3.000+ dataset pemerintah, menggunakan Sentence-BERT dan kesamaan TF-IDF untuk pencocokan data regional, dan mengonfigurasi pipeline ETL dengan Apache NiFi dan Airflow.',
                        tools: ['Sentence-BERT', 'TF-IDF', 'Airflow'],
                        highlights: [
                            'Membangun modul pembersihan data otomatis untuk 3000+ dataset pemerintahan.',
                            'Menggunakan arsitektur Sentence-BERT dan TF-IDF untuk mencocokkan kemiripan data regional.',
                            'Mengkonfigurasi alur ETL (Extract, Transform, Load) menggunakan Apache NiFi.',
                            'Mengorkestrasi pipeline pemrosesan data dengan Apache Airflow.'
                        ],
                        demoUrl: 'https://seal.or.id'
                    },
                    {
                        period: 'Sep - Des 2024',
                        title: 'Student Machine Learning',
                        org: 'Bangkit Academy 2024',
                        image: [Dashboard_Owner_jpg_1.default, file_2024_06_01_04_50_40_png_1.default, file_2024_06_01_04_49_33_png_1.default],
                        focus: 'Applied ML dan deployment',
                        impact: 'Membangun solusi pertanian berbasis model dengan akurasi terukur dan pengakuan formal melalui sertifikasi dan kelulusan dengan predikat.',
                        summary: 'Membangun TomKits untuk deteksi penyakit tomat menggunakan EfficientNet dengan akurasi 98% dan mendapatkan TensorFlow Developer Professional Certificate serta Graduate Distinction.',
                        tools: ['EfficientNet', 'Flask', 'REST API'],
                        highlights: [
                            'Lulus dengan predikat Distinction (Top Graduate) dari program Bangkit Academy.',
                            'Melatih model EfficientNet untuk deteksi penyakit tomat dengan akurasi 98%.',
                            'Mendeploy model ke dalam REST API menggunakan Flask.',
                            'Mendapatkan sertifikasi TensorFlow Developer Professional.'
                        ],
                        repoUrl: 'https://github.com/ziee2'
                    }
                ]
            },
            projects: {
                title: 'Proyek Unggulan',
                copy: 'Sekarang proyek saya buat lebih premium: filter kategori, split showcase, dan area masonry untuk eksplorasi proyek lanjutan.',
                tracks: ['Semua', 'AI Engineer', 'Data', 'Software Development', 'Game Development'],
                showingParams: function (count, track) { return "Menampilkan ".concat(count, " proyek di kategori ").concat(track === 'Semua' ? 'semua area' : track, "."); },
                showMore: 'Lihat selengkapnya',
                hideMore: 'Sembunyikan proyek lain',
                seeMore: 'Lihat selengkapnya',
                detail: 'Detail',
                seeDetail: 'Lihat detail',
                close: 'Tutup',
                highlights: 'Highlight Proyek',
                seeGithub: 'Lihat GitHub',
                seeDemo: 'Lihat Demo',
                items: [
                    {
                        title: 'AI Assistant Chatbot for Pharmacy POS',
                        category: 'LLM · RAG · NLP',
                        period: 'Apr 2026',
                        image: [Dashboard_Owner_jpg_1.default, file_2024_06_01_04_49_33_png_1.default, file_2024_06_01_04_50_40_png_1.default],
                        tracks: ['AI Engineer'],
                        featured: true,
                        outcome: 'Menambahkan dukungan pencarian semantik dan rekomendasi obat untuk alur kerja apotek.',
                        summary: 'Chatbot RAG (retrieval-augmented generation) hybrid dengan LangChain, FAISS, LLM lokal via Ollama, pencarian semantik Sentence-BERT, dan integrasi FastAPI untuk rekomendasi pengobatan.',
                        stack: ['LangChain', 'FAISS', 'Ollama'],
                        repoUrl: 'https://huggingface.co/models',
                        repoLabel: 'Hugging Face',
                        demoUrl: 'https://demo-website.com',
                        demoLabel: 'Kunjungi Website',
                        highlights: ['RAG pipeline untuk data obat', 'Pencarian semantik dengan Sentence-BERT', 'Integrasi FastAPI ke alur POS'],
                    },
                    {
                        title: 'AI Public Speaking Coach',
                        category: 'Computer Vision · Speech · NLP',
                        period: 'Nov 2025',
                        image: file_2024_06_01_04_49_33_png_1.default,
                        tracks: ['AI Engineer'],
                        featured: true,
                        outcome: 'Mengubah sinyal multimodal menjadi umpan balik yang dapat ditindaklanjuti untuk performa berbicara.',
                        summary: 'Sistem AI multi-modal menggunakan MediaPipe, YOLO, BERT, Wav2Vec2, dan Silero VAD untuk menganalisis postur, artikulasi, kata pengisi, tempo, dan relevansi topik.',
                        stack: ['MediaPipe', 'YOLO', 'BERT'],
                        repoUrl: 'https://github.com/ziee2',
                        highlights: ['Analisis pose dan gesture real-time', 'Evaluasi suara dan tempo bicara', 'Rekomendasi yang langsung bisa ditindaklanjuti'],
                    },
                    {
                        title: 'Chicken Manure Scan Application',
                        category: 'Computer Vision',
                        period: 'Mei 2024',
                        image: file_2024_06_01_04_50_40_png_1.default,
                        tracks: ['AI Engineer', 'Data'],
                        featured: true,
                        outcome: 'Menghasilkan akurasi 98% untuk deteksi penyakit dan menghubungkan model ke stack REST API.',
                        summary: 'Aplikasi deteksi penyakit berbasis CNN menggunakan EfficientNetB3 dengan akurasi 98% dan integrasi REST API melalui Flask dan Laravel.',
                        stack: ['EfficientNetB3', 'Flask', 'Laravel'],
                        repoUrl: 'https://github.com/ziee2',
                        highlights: ['Model klasifikasi berbasis EfficientNetB3', 'API inference untuk integrasi aplikasi', 'Akurasi hingga 98% pada evaluasi internal'],
                    },
                    {
                        title: 'ChiCheck',
                        summary: 'Sistem pemindaian kesehatan ayam dan pengumpulan data berbasis web untuk peternak.',
                        image: Dashboard_Owner_jpg_1.default,
                        category: 'Data Platform',
                        period: '2024',
                        tracks: ['Data', 'Software Development'],
                        featured: false,
                        outcome: 'Berfokus pada pengumpulan, inspeksi, dan penanganan data untuk alur kerja peternakan.',
                        stack: ['PHP', 'MySQL', 'Dashboard'],
                        repoUrl: 'https://github.com/ziee2/ChiCheck-WEB.git',
                        highlights: ['Pengelolaan data telur, pakan, dan ayam', 'Fitur scan kesehatan ayam', 'Dashboard operasional peternakan'],
                    },
                    {
                        title: 'FlyPaper',
                        summary: 'Proyek game endless runner.',
                        image: file_2024_06_01_04_49_33_png_1.default,
                        category: 'Game Development',
                        period: '2024',
                        tracks: ['Game Development'],
                        featured: false,
                        outcome: 'Menunjukkan eksekusi produk di luar AI melalui build interaktif yang dipoles.',
                        stack: ['Unity', 'Game Design'],
                        repoUrl: 'https://github.com/Bee3-Team/Bee3',
                        highlights: ['Game loop endless runner', 'Iterasi gameplay berbasis feedback', 'Eksekusi produk dari ide ke prototipe'],
                    },
                    {
                        title: 'I-Care',
                        summary: 'Proyek Express.js dan Socket.io untuk pembuatan bot kustom.',
                        image: file_2024_06_01_04_50_40_png_1.default,
                        category: 'Web App',
                        period: '2024',
                        tracks: ['Software Development'],
                        featured: false,
                        outcome: 'Mendemonstrasikan rekayasa web realtime dan orkestrasi layanan.',
                        stack: ['Express.js', 'Socket.io'],
                        repoUrl: 'https://github.com/Vins2106/zhat.cf',
                        highlights: ['Komunikasi real-time berbasis Socket.io', 'Integrasi bot service dengan Node.js', 'Arsitektur backend modular'],
                    },
                    {
                        title: 'Apple Leaf Rust Disease Segmentation',
                        summary: 'Computer vision segmentasi penyakit rust pada daun menggunakan Mask R-CNN dengan 3 backbone (ResNet50V2, EfficientNetB4, DenseNet201) dan anotasi data.',
                        image: Dashboard_Owner_jpg_1.default,
                        category: 'Computer Vision',
                        period: '2026',
                        tracks: ['AI Engineer'],
                        featured: false,
                        outcome: 'Membandingkan performa 3 backbone pada arsitektur Mask R-CNN untuk segmentasi gambar daun secara presisi.',
                        stack: ['Mask R-CNN', 'ResNet50V2', 'EfficientNetB4', 'DenseNet201'],
                        highlights: ['Anotasi data citra penyakit karat pada daun', 'Pelatihan model Mask R-CNN dengan 3 backbone berbeda', 'Evaluasi performa segmentasi instance'],
                    },
                    {
                        title: 'Computer Vision & IoT (Snack & Mouse Detection)',
                        summary: 'Personal project mendeteksi objek menggunakan YOLO dan mengintegrasikannya dengan Arduino Uno.',
                        image: file_2024_06_01_04_50_40_png_1.default,
                        category: 'Computer Vision · IoT',
                        period: 'Personal Project',
                        tracks: ['AI Engineer'],
                        featured: false,
                        outcome: 'Mengotomatisasi respon perangkat keras (lampu berkedip lambat/cepat) berdasarkan deteksi objek dari kamera.',
                        stack: ['YOLO', 'Arduino Uno', 'Python'],
                        highlights: ['Deteksi objek real-time dengan YOLO', 'Integrasi hardware menggunakan serial Arduino', 'Sistem respon otomatis berbasis plug in/plug off'],
                    },
                    {
                        title: 'Product Review Sentiment Analysis',
                        summary: 'Proyek analisis sentimen pada ulasan aplikasi Shopee dari Play Store menggunakan model deep learning.',
                        image: file_2024_06_01_04_49_33_png_1.default,
                        category: 'NLP · Deep Learning',
                        period: 'Mei 2025',
                        tracks: ['AI Engineer'],
                        featured: false,
                        outcome: 'Melakukan klasifikasi sentimen menggunakan pendekatan GRU, LSTM, dan CNN.',
                        stack: ['GRU', 'LSTM', 'CNN', 'Web Scraping'],
                        highlights: ['Web scraping ulasan aplikasi Shopee di Play Store', 'Pemrosesan bahasa alami (NLP) untuk teks bahasa Indonesia', 'Evaluasi performa klasifikasi GRU, LSTM, dan CNN'],
                    },
                    {
                        title: 'Anime Recommendation System',
                        summary: 'Membangun mesin rekomendasi anime menggunakan pendekatan collaborative filtering (user-based & item-based).',
                        image: Dashboard_Owner_jpg_1.default,
                        category: 'Machine Learning',
                        period: 'Apr 2025',
                        tracks: ['AI Engineer'],
                        featured: false,
                        outcome: 'Memberikan rekomendasi anime terpersonalisasi berdasarkan kemiripan pola kesukaan pengguna.',
                        stack: ['Collaborative Filtering', 'Python', 'Pandas'],
                        highlights: ['Implementasi user-based collaborative filtering', 'Implementasi item-based collaborative filtering', 'Analisis matriks kemiripan untuk rekomendasi'],
                    },
                    {
                        title: 'Company Profile Website CV EHPRA Farm',
                        summary: 'Website company profile untuk CV EHPRA Farm yang dibangun menggunakan HTML dan CSS.',
                        image: Dashboard_Owner_jpg_1.default,
                        category: 'Web Development',
                        period: '2024',
                        tracks: ['Software Development'],
                        featured: false,
                        outcome: 'Menyediakan profil digital yang interaktif dan responsif untuk keperluan bisnis perusahaan.',
                        stack: ['HTML', 'CSS'],
                        demoUrl: 'http://cvehprafarm.com/',
                        demoLabel: 'Kunjungi Website',
                        highlights: ['Desain antarmuka responsif', 'Pengembangan murni menggunakan HTML dan CSS', 'Struktur website yang SEO-friendly'],
                    },
                    {
                        title: 'Kasir-Sehatku',
                        summary: 'Aplikasi kasir apotek berbasis web untuk mengelola transaksi dan inventaris obat.',
                        image: Dashboard_Owner_jpg_1.default,
                        category: 'Web App',
                        period: '2024',
                        tracks: ['Software Development'],
                        featured: false,
                        outcome: 'Mempermudah pencatatan transaksi harian dan manajemen stok obat secara efisien.',
                        stack: ['Laravel', 'PHP', 'MySQL'],
                        demoUrl: 'http://kasir-sehatku.com/',
                        demoLabel: 'Kunjungi Website',
                        highlights: ['Manajemen stok dan inventaris obat', 'Pencatatan transaksi kasir harian', 'Dibangun menggunakan framework Laravel'],
                    }
                ]
            },
            skills: {
                title: 'Keahlian',
                copy: 'Bagian keahlian disusun menjadi tiga pilar agar recruiter langsung melihat kekuatan teknis utama, bukan sekadar daftar tools.',
                groups: [
                    { title: 'AI / ML', items: ['Python', 'TensorFlow', 'PyTorch', 'Keras', 'Hugging Face', 'Flask', 'FastAPI'] },
                    { title: 'Data', items: ['SQL', 'MySQL', 'PostgreSQL', 'ETL', 'Apache NiFi', 'Airflow', 'Web Scraping'] },
                    { title: 'Web / Deployment', items: ['PHP', 'JavaScript', 'Laravel', 'Docker', 'REST API', 'Git', 'Agile collaboration'] },
                ]
            },
            certificates: {
                title: 'Sertifikat',
                copy: 'Koleksi sertifikat tetap ditampilkan sebagai bukti pendukung kompetensi dan konsistensi pembelajaran di jalur AI/Data.',
            },
            closing: {
                note: 'Closing note',
                title: 'Berorientasi solusi dan siap berkontribusi pada produk AI yang berdampak.',
                desc: 'Struktur baru ini dibuat lebih premium, tidak pasaran, dan lebih visual sehingga value proyekmu terbaca kuat oleh recruiter maupun hiring manager.'
            }
        }
    },
    en: {
        nav: [
            { id: 'about', label: 'About' },
            { id: 'experience', label: 'Experience' },
            { id: 'projects', label: 'Projects' },
            { id: 'skills', label: 'Skills' },
            { id: 'certificates', label: 'Certificates' },
        ],
        hero: {
            badge: 'Premium AI Portfolio',
            title: 'Building practical AI systems for real-world problems.',
            desc: 'Computer Science graduate from University of Jember focusing on Computer Vision, NLP, data cleansing, and model deployment. This design is tailored to make your profile look premium, composed, and strong for recruitment purposes.',
            exploreBtn: 'Explore Projects',
            proofBtn: 'View Evidence',
            profileSnapshot: 'Profile snapshot',
            profileSubtitle: 'AI focus with real project depth',
            currentDirection: 'Current direction',
            currentDirectionDesc: 'with a focus on computer vision, NLP, data pipelines, and product-ready deployment.',
        },
        valueProps: [
            'I build AI products, not just train models.',
            'My approach combines research with direct implementation.',
            'The portfolio structure is editorialized for quick HR comprehension.',
            'Work evidence is displayed through project visuals, dashboards, and certificates.',
        ],
        sections: {
            about: {
                title: 'About Me',
                copy: 'A fresh graduate, specializing in Artificial Intelligence (AI), specifically Computer Vision and Natural Language Processing (NLP). Experienced in building end-to-end innovative solutions, ranging from machine learning model development (TensorFlow, PyTorch) and data analysis with Python, to deploying models as REST APIs using Flask, FastAPI, and Docker. Accustomed to working systematically and in an organized manner, ready to contribute in dynamic teams to develop AI products and solve real-world industry challenges.',
                bgTitle: 'Education & Achievements',
                bgSchool: 'University of Jember',
                bgLogo: 'https://upload.wikimedia.org/wikipedia/id/3/3a/Logo_Universitas_Jember.png',
                bgPeriod: '2021 - Present',
                bgGpa: '3.90 / 4.00',
                bgDegree: 'Bachelor of Informatics, Faculty of Computer Science',
                bgThesis: 'Thesis: Performance comparison of ResNet50V2, EfficientNetB4, and DenseNet201 in Mask R-CNN for rust disease segmentation in apple leaves.',
                achTitle: 'Achievements',
                achSubtitle: 'Competitive, practical, and project-driven',
                achDesc: 'Finalist of the Student Digital Innovation Competition, 3rd place in Laos development by UKM Linux & Open Source, and Graduate Distinction from Bangkit Academy.'
            },
            experience: {
                title: 'Experience',
                copy: 'I use a professional timeline format: each work phase has visuals, context, tools, and clear impact so your progression is stronger in the eyes of HR.',
                items: [
                    {
                        period: 'February - April 2026',
                        title: 'Software Development',
                        org: 'Freelance',
                        image: [Dashboard_Owner_jpg_1.default, file_2024_06_01_04_50_40_png_1.default, file_2024_06_01_04_49_33_png_1.default],
                        focus: 'Full-Stack Web Development & AI Integration',
                        impact: 'Improved pharmacy operational automation through an AI-integrated web-based POS system.',
                        summary: 'Designed and built a web application independently from scratch (Full-Stack), managing the entire development cycle from the user interface (Front-End) to the server system and database (Back-End). Built a web-based point-of-sale (POS) and pharmacy inventory management system, integrating specific Artificial Intelligence (AI) features to enhance operational automation, complete with access rights and employee shift management systems.',
                        tools: ['Full-Stack', 'Web App', 'AI Integration', 'POS'],
                        highlights: [
                            'Designed and built a full-stack web application independently from scratch.',
                            'Managed the entire development cycle from Front-End to Back-End.',
                            'Built a web-based POS and pharmacy inventory management system.',
                            'Integrated custom Artificial Intelligence (AI) features for operational automation.',
                            'Implemented role-based access control and employee shift management.'
                        ]
                    },
                    {
                        period: 'Sep - Dec 2025',
                        title: 'Teaching Assistant',
                        org: 'Lab. AI University of Jember',
                        image: [file_2024_06_01_04_49_33_png_1.default, file_2024_06_01_04_50_40_png_1.default, Dashboard_Owner_jpg_1.default],
                        focus: 'AI education and lab support',
                        impact: 'Helped students understand computer vision, visualization, and deep learning implementation through guided sessions and assignment feedback.',
                        summary: 'Guided lab sessions for Computer Vision and Data Visualization using Python, OpenCV, TensorFlow, and visualization libraries. Prepared materials, demonstrated techniques, and evaluated assignments around image processing and deep learning.',
                        tools: ['Computer Vision', 'Data Visualization', 'Python', 'OpenCV', 'TensorFlow', 'Matplotlib'],
                        highlights: [
                            'Guided lab sessions for 50+ students on Computer Vision and Data Visualization.',
                            'Prepared lab materials based on Python, OpenCV, and modern visualization libraries.',
                            'Demonstrated deep learning techniques and evaluated student implementations.',
                            'Assisted in troubleshooting TensorFlow models built by students.'
                        ],
                        demoUrl: 'https://unej.ac.id'
                    },
                    {
                        period: 'Feb - Jun 2025',
                        title: 'Data Scientist Intern',
                        org: 'Social Economic Accelerator Lab (SEAL)',
                        image: [file_2024_06_01_04_50_40_png_1.default, file_2024_06_01_04_49_33_png_1.default, Dashboard_Owner_jpg_1.default],
                        focus: 'Data engineering and cleansing',
                        impact: 'Improved dataset consistency across 3,000+ government records and reduced merge issues through semantic matching workflows.',
                        summary: 'Built an automated cleansing module for 3,000+ government datasets, used Sentence-BERT and TF-IDF similarity for regional data matching, and configured ETL pipelines with Apache NiFi and Airflow.',
                        tools: ['Sentence-BERT', 'TF-IDF', 'Airflow'],
                        highlights: [
                            'Built an automated data cleansing module for 3000+ government datasets.',
                            'Utilized Sentence-BERT and TF-IDF architectures to match regional data similarities.',
                            'Configured ETL (Extract, Transform, Load) pipelines using Apache NiFi.',
                            'Orchestrated data processing pipelines with Apache Airflow.'
                        ],
                        demoUrl: 'https://seal.or.id'
                    },
                    {
                        period: 'Sep - Dec 2024',
                        title: 'Student Machine Learning',
                        org: 'Bangkit Academy 2024',
                        image: [Dashboard_Owner_jpg_1.default, file_2024_06_01_04_50_40_png_1.default, file_2024_06_01_04_49_33_png_1.default],
                        focus: 'Applied ML and deployment',
                        impact: 'Built a model-driven agriculture solution with measurable accuracy and formal recognition through certification and graduate distinction.',
                        summary: 'Built TomKits for tomato disease detection using EfficientNet with 98% accuracy and earned TensorFlow Developer Professional Certificate plus Graduate Distinction.',
                        tools: ['EfficientNet', 'Flask', 'REST API'],
                        highlights: [
                            'Graduated with Distinction (Top Graduate) from the Bangkit Academy program.',
                            'Trained an EfficientNet model for tomato disease detection with 98% accuracy.',
                            'Deployed the model into a REST API using Flask.',
                            'Earned the TensorFlow Developer Professional certification.'
                        ],
                        repoUrl: 'https://github.com/ziee2'
                    }
                ]
            },
            projects: {
                title: 'Featured Projects',
                copy: 'Projects are now presented more premium: category filters, showcase splits, and a masonry area for further project exploration.',
                tracks: ['All', 'AI Engineer', 'Data', 'Software Development', 'Game Development'],
                showingParams: function (count, track) { return "Showing ".concat(count, " projects in ").concat(track === 'All' ? 'all areas' : track, "."); },
                showMore: 'View more',
                hideMore: 'Hide other projects',
                seeMore: 'View more',
                detail: 'Detail',
                seeDetail: 'View details',
                close: 'Close',
                highlights: 'Project Highlights',
                seeGithub: 'View GitHub',
                seeDemo: 'View Demo',
                items: [
                    {
                        title: 'AI Assistant Chatbot for Pharmacy POS',
                        category: 'LLM · RAG · NLP',
                        period: 'Apr 2026',
                        image: [Dashboard_Owner_jpg_1.default, file_2024_06_01_04_49_33_png_1.default, file_2024_06_01_04_50_40_png_1.default],
                        tracks: ['AI Engineer'],
                        featured: true,
                        outcome: 'Added semantic retrieval and medication recommendation support for a pharmacy workflow.',
                        summary: 'Hybrid retrieval-augmented generation chatbot with LangChain, FAISS, local LLM via Ollama, Sentence-BERT semantic search, and FastAPI integration for medication recommendations.',
                        stack: ['LangChain', 'FAISS', 'Ollama'],
                        repoUrl: 'https://huggingface.co/models',
                        repoLabel: 'Hugging Face',
                        demoUrl: 'https://demo-website.com',
                        demoLabel: 'Visit Website',
                        highlights: ['RAG pipeline for medication data', 'Semantic search with Sentence-BERT', 'FastAPI integration into POS flow'],
                    },
                    {
                        title: 'AI Public Speaking Coach',
                        category: 'Computer Vision · Speech · NLP',
                        period: 'Nov 2025',
                        image: file_2024_06_01_04_49_33_png_1.default,
                        tracks: ['AI Engineer'],
                        featured: true,
                        outcome: 'Turned multimodal signals into actionable feedback for speaking performance.',
                        summary: 'Multi-modal AI system using MediaPipe, YOLO, BERT, Wav2Vec2, and Silero VAD to analyze posture, articulation, filler words, tempo, and topic relevance.',
                        stack: ['MediaPipe', 'YOLO', 'BERT'],
                        repoUrl: 'https://github.com/ziee2',
                        highlights: ['Real-time pose and gesture analysis', 'Voice and speaking tempo evaluation', 'Actionable recommendations'],
                    },
                    {
                        title: 'Chicken Manure Scan Application',
                        category: 'Computer Vision',
                        period: 'May 2024',
                        image: file_2024_06_01_04_50_40_png_1.default,
                        tracks: ['AI Engineer', 'Data'],
                        featured: true,
                        outcome: 'Delivered 98% accuracy for disease detection and connected the model to a REST API stack.',
                        summary: 'CNN-based disease detection app using EfficientNetB3 with 98% accuracy and REST API integration through Flask and Laravel.',
                        stack: ['EfficientNetB3', 'Flask', 'Laravel'],
                        repoUrl: 'https://github.com/ziee2',
                        highlights: ['EfficientNetB3-based classification model', 'Inference API for app integration', 'Up to 98% accuracy on internal evaluation'],
                    },
                    {
                        title: 'ChiCheck',
                        summary: 'Website-based chicken health scanning and data collection system for breeders.',
                        image: Dashboard_Owner_jpg_1.default,
                        category: 'Data Platform',
                        period: '2024',
                        tracks: ['Data', 'Software Development'],
                        featured: false,
                        outcome: 'Focused on collection, inspection, and data handling for breeding workflows.',
                        stack: ['PHP', 'MySQL', 'Dashboard'],
                        repoUrl: 'https://github.com/ziee2/ChiCheck-WEB.git',
                        highlights: ['Management of egg, feed, and chicken data', 'Chicken health scanning feature', 'Farm operational dashboard'],
                    },
                    {
                        title: 'FlyPaper',
                        summary: 'Endless runner game project.',
                        image: file_2024_06_01_04_49_33_png_1.default,
                        category: 'Game Development',
                        period: '2024',
                        tracks: ['Game Development'],
                        featured: false,
                        outcome: 'Shows product execution beyond AI through a polished interactive build.',
                        stack: ['Unity', 'Game Design'],
                        repoUrl: 'https://github.com/Bee3-Team/Bee3',
                        highlights: ['Endless runner game loop', 'Feedback-driven gameplay iteration', 'Product execution from idea to prototype'],
                    },
                    {
                        title: 'I-Care',
                        summary: 'Express.js and Socket.io project for custom bot creation.',
                        image: file_2024_06_01_04_50_40_png_1.default,
                        category: 'Web App',
                        period: '2024',
                        tracks: ['Software Development'],
                        featured: false,
                        outcome: 'Demonstrates realtime web engineering and service orchestration.',
                        stack: ['Express.js', 'Socket.io'],
                        repoUrl: 'https://github.com/Vins2106/zhat.cf',
                        highlights: ['Real-time communication using Socket.io', 'Bot service integration with Node.js', 'Modular backend architecture'],
                    },
                    {
                        title: 'Apple Leaf Rust Disease Segmentation',
                        summary: 'Computer vision rust disease segmentation on leaves using Mask R-CNN with 3 backbones (ResNet50V2, EfficientNetB4, DenseNet201) and custom data annotation.',
                        image: Dashboard_Owner_jpg_1.default,
                        category: 'Computer Vision',
                        period: '2026',
                        tracks: ['AI Engineer'],
                        featured: false,
                        outcome: 'Compared the performance of 3 backbones in Mask R-CNN architecture for precise leaf image segmentation.',
                        stack: ['Mask R-CNN', 'ResNet50V2', 'EfficientNetB4', 'DenseNet201'],
                        highlights: ['Annotated rust disease images on leaves', 'Trained Mask R-CNN models with 3 different backbones', 'Evaluated instance segmentation performance'],
                    },
                    {
                        title: 'Computer Vision & IoT (Snack & Mouse Detection)',
                        summary: 'Personal project detecting objects using YOLO and integrating with Arduino Uno.',
                        image: file_2024_06_01_04_50_40_png_1.default,
                        category: 'Computer Vision · IoT',
                        period: 'Personal Project',
                        tracks: ['AI Engineer'],
                        featured: false,
                        outcome: 'Automated hardware responses (slow/fast blinking LED) based on camera object detection.',
                        stack: ['YOLO', 'Arduino Uno', 'Python'],
                        highlights: ['Real-time object detection with YOLO', 'Hardware integration via Arduino serial', 'Automated response system based on plug in/plug off logic'],
                    },
                    {
                        title: 'Product Review Sentiment Analysis',
                        summary: 'Sentiment analysis project on Shopee app reviews from the Play Store using deep learning models.',
                        image: file_2024_06_01_04_49_33_png_1.default,
                        category: 'NLP · Deep Learning',
                        period: 'May 2025',
                        tracks: ['AI Engineer'],
                        featured: false,
                        outcome: 'Performed sentiment classification using GRU, LSTM, and CNN approaches.',
                        stack: ['GRU', 'LSTM', 'CNN', 'Web Scraping'],
                        highlights: ['Web scraped Shopee app reviews from Play Store', 'Natural Language Processing (NLP) for Indonesian text', 'Evaluated GRU, LSTM, and CNN classification performance'],
                    },
                    {
                        title: 'Anime Recommendation System',
                        summary: 'Built an anime recommendation engine using collaborative filtering approaches (user-based & item-based).',
                        image: Dashboard_Owner_jpg_1.default,
                        category: 'Machine Learning',
                        period: 'Apr 2025',
                        tracks: ['AI Engineer'],
                        featured: false,
                        outcome: 'Provided personalized anime recommendations based on user preference patterns.',
                        stack: ['Collaborative Filtering', 'Python', 'Pandas'],
                        highlights: ['Implemented user-based collaborative filtering', 'Implemented item-based collaborative filtering', 'Analyzed similarity matrices for recommendations'],
                    },
                    {
                        title: 'Company Profile Website CV EHPRA Farm',
                        summary: 'Company profile website for CV EHPRA Farm built using HTML and CSS.',
                        image: Dashboard_Owner_jpg_1.default,
                        category: 'Web Development',
                        period: '2024',
                        tracks: ['Software Development'],
                        featured: false,
                        outcome: 'Provided an interactive and responsive digital profile for the company’s business needs.',
                        stack: ['HTML', 'CSS'],
                        demoUrl: 'http://cvehprafarm.com/',
                        demoLabel: 'Visit Website',
                        highlights: ['Responsive interface design', 'Pure development using HTML and CSS', 'SEO-friendly website structure'],
                    },
                    {
                        title: 'Kasir-Sehatku',
                        summary: 'Web-based pharmacy cashier application to manage transactions and medicine inventory.',
                        image: Dashboard_Owner_jpg_1.default,
                        category: 'Web App',
                        period: '2024',
                        tracks: ['Software Development'],
                        featured: false,
                        outcome: 'Simplified daily transaction recording and medicine stock management efficiently.',
                        stack: ['Laravel', 'PHP', 'MySQL'],
                        demoUrl: 'http://kasir-sehatku.com/',
                        demoLabel: 'Visit Website',
                        highlights: ['Medicine stock and inventory management', 'Daily cashier transaction recording', 'Built using the Laravel framework'],
                    }
                ]
            },
            skills: {
                title: 'Skills',
                copy: 'The skills section is structured into three pillars so recruiters can immediately see core technical strengths, rather than just a list of tools.',
                groups: [
                    { title: 'AI / ML', items: ['Python', 'TensorFlow', 'PyTorch', 'Keras', 'Hugging Face', 'Flask', 'FastAPI'] },
                    { title: 'Data', items: ['SQL', 'MySQL', 'PostgreSQL', 'ETL', 'Apache NiFi', 'Airflow', 'Web Scraping'] },
                    { title: 'Web / Deployment', items: ['PHP', 'JavaScript', 'Laravel', 'Docker', 'REST API', 'Git', 'Agile collaboration'] },
                ]
            },
            certificates: {
                title: 'Certificates',
                copy: 'A collection of certificates is displayed as supporting evidence of competence and consistent learning in the AI/Data track.',
            },
            closing: {
                note: 'Closing note',
                title: 'Solution-oriented and ready to contribute to impactful AI products.',
                desc: 'This new structure is made to be more premium, distinct, and visual so your project value is strongly perceived by both recruiters and hiring managers.'
            }
        }
    }
};
